import Head from 'next/head'
import React from 'react'

import 'bootstrap/dist/css/bootstrap.min.css'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Portifólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main></main>
    </div>
  )
}

export default Home
