import Head from 'next/head'
import PessoalHome from '../assets/perfil 2.png'
import Logo from '../assets/logo.svg'

import { Container } from '../styles/pages/home'


const Home: React.FC = () =>{
  return (
    <Container>
      <Head>
        <title>Portifólio</title>
        <meta name="description" content="Generated by create next app" />

      </Head>

      <h1>André Luiz Santos</h1>
      <p>Front-end Developer</p>

    </Container>
  )
}

export default Home
